pipelines:
  default:
    - step:
        name: Build and Install
        caches:
          - node
        script:
          # Naviguer dans le répertoire 'my-react-app'
          - cd my-react-app
          # Installer les dépendances depuis le package.json
          - npm install
          # Ajoutez d'autres commandes si nécessaire (par exemple, build ou test)
