image: node:16  # Utilisation de l'image Docker officielle Node.js version 16

pipelines:
  default:
    - step:
        name: "Installer les dépendances"
        caches:
          - node
        script:
          - npm install  # Installe les dépendances
    - step:
        name: "Exécuter les tests"
        script:
          - npm test  # Lance les tests unitaires
    - step:
        name: "Construire l'application"
        script:
          - npm run build  # Compile l'application React pour la production
