image: node:16  # Utilisation d'une image Docker contenant Node.js

pipelines:
  default:
    - step:
        name: Build Only
        caches:
          - node
        script:
          - npm install   # Installe les dépendances
          - npm run build  # Effectue le build de votre application
