name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Version Node.js

      # Spécifie le répertoire de travail
      - name: Install dependencies
        working-directory: my-react-app  # Spécifie le dossier du projet
        run: npm install

      # Si tu as des tests
      - name: Run tests
        working-directory: my-react-app  # Spécifie le dossier du projet
        run: npm test

      - name: Build project
        working-directory: my-react-app  # Spécifie le dossier du projet
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
