jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List files in project directory
        run: ls -alh my-react-app

      - name: Install dependencies
        working-directory: my-react-app
        run: npm install

      - name: Run tests
        working-directory: my-react-app
        run: npm test

      - name: Build project
        working-directory: my-react-app
        run: npm run build
