name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Version Node.js

      - name: Install dependencies
        working-directory: my-react-app  # Spécifie le dossier du projet
        run: npm install

      # Si tu as des tests
      # - name: Run tests
      #   run: npm test

      - name: Build project
        working-directory: my-react-app  # Spécifie le dossier du projet
        run: npm run build

 